// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: References.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 10002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(900a370ddc2fbe15);
enum class ReferenceType_900a370ddc2fbe15: uint16_t {
  ROOT,
  ROOT_VALUE,
  PARENT,
};
CAPNP_DECLARE_ENUM(ReferenceType, 900a370ddc2fbe15);
CAPNP_DECLARE_SCHEMA(9285cac596a6bd07);
enum class ImplementationType_9285cac596a6bd07: uint16_t {
  ENUMERATOR,
};
CAPNP_DECLARE_ENUM(ImplementationType, 9285cac596a6bd07);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::ReferenceType_900a370ddc2fbe15 ReferenceType;

typedef ::capnp::schemas::ImplementationType_9285cac596a6bd07 ImplementationType;

// =======================================================================================

// =======================================================================================


CAPNP_END_HEADER

